version: "3.8"

services:

  noip:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=bplusbot,wborbajr
      - TOKEN=${DUCK_TOKEN}
      - LOG_FILE=false
    restart: always

  bplusbot:
    stdin_open: true
    tty: true
    container_name: ct_bpbot
    hostname: bpbot
    image: bpbot:latest1
    restart: always
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    # volumes:
    #   - $PWD/xml:/nfeimport/xml:rw
    #   - $PWD/.:/nfeimport:rw
    networks:
      - infra
    ports:
      - 3001:3443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  infra:
    driver: bridge