version: "3.8"

services:

  # noip:
  #   image: ghcr.io/linuxserver/duckdns
  #   container_name: duckdns
  #   environment:
  #     - PUID=1000 #optional
  #     - PGID=1000 #optional
  #     - TZ=America/Sao_Paulo
  #     - SUBDOMAINS=${DUCK_SUBDOMAINS}
  #     - TOKEN=${DUCK_TOKEN}
  #     - LOG_FILE=false
  #   restart: always

  bplusbot:
    stdin_open: true
    tty: true
    container_name: ${CONTAINER}
    hostname: ${PROJECT_NAME}
    image: ${DOCKER_USER}/${PROJECT_NAME}:${DOCKER_TAG}
    restart: always
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    # volumes:
    #   - $PWD/xml:/nfeimport/xml:rw
    #   - $PWD/.:/nfeimport:rw
    networks:
      - infra
    ports:
      - 3001:3443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  infra:
    driver: bridge